---
title: "Analyse Statistique de Données Energétiques"
author: "Votre nom"
date: "`r Sys.Date()`"
output: 
  word_document:
    fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 7, fig.height = 5, dev = "png", fig.show = TRUE) # Chargement des bibliothèques nécessaires
library(ggplot2)
library(dplyr)
library(corrplot)

# Lecture des données (corriger le chemin vers votre fichier)
data <- read.csv("C:/Users/Utilisateur/Documents/Cours BUT 2éme année/R studio/logement_finale.csv", 
                 sep = ",", dec = ".", header = TRUE)

# Aperçu des données
head(data)
summary(data)# Statistiques descriptives des coûts et surfaces
summary(data[c("Coût_chauffage", "Coût_éclairage", "Coût_ECS", "Surface_habitable_logement")])# Sélection des variables pour la corrélation
vars <- data[c("Coût_chauffage", "Coût_éclairage", "Coût_ECS", "Surface_habitable_logement")]

# Matrice de corrélation
cor_matrix <- cor(vars, use = "complete.obs")

# Affichage de la matrice de corrélation
corrplot(cor_matrix, method = "circle")# Régression linéaire : Coût de chauffage ~ Surface habitable
lm_chauffage_surface <- lm(Coût_chauffage ~ Surface_habitable_logement, data = data)

# Résultats du modèle
summary(lm_chauffage_surface)

# Graphique de la régression
ggplot(data, aes(x = Surface_habitable_logement, y = Coût_chauffage)) +
  geom_point() +
  geom_smooth(method = "lm", col = "red") +
  labs(title = "Régression linéaire : Coût de chauffage vs Surface habitable",
       x = "Surface habitable (m²)", y = "Coût de chauffage (€)")
